baseURL: "https://sangwon-hyun.github.io/"
title: "Sangwon Hyun"
theme: "papermod"

# System settings must come before Params
taxonomies:
  tag: tags
  category: categories

publishDir: "docs"
buildDrafts: false

# Everything below this is theme-specific
params:
  mainSections:
    - posts
  showPostMeta: true
  showTags: true
  profileMode:
    enabled: true
    title: "Sangwon (Justin) Hyun"
    subtitle: "Assistant Professor of Statistics, UC Santa Cruz"
    # imageUrl: "img/resized-pic.jpg"
    imageUrl: "https://sangwon-hyun.github.io/img/resized-pic.jpg"
    imageWidth: 250
    imageHeight: 250
    buttons:
      - name: About me
        url: /posts/about-me
      - name: Research
        url: /posts/research
      - name: Group
        url: /posts/group