baseURL: https://sangwon-hyun.github.io
title: Sangwon Hyun
date: ""
publishDir: "docs"
description: This is a description 
theme: "papermod"
params:
    profileMode:
        social: true
        enabled: true
        title: "Sangwon (Justin) Hyun" # optional default will be site title
        subtitle: "Assistant Professor of Statistics, UC Santa Cruz"
        imageUrl: "https://github.com/sangwon-hyun/sangwon-hyun.github.io/blob/master/boston-mit-square.jpg?raw=true"
        imageWidth: 250 # custom size
        imageHeight: 250 # custom size
        buttons:
        - name: About me
          url: about-me
        - name: Research
          url: research
        - name: Group
          url: group